version: "3.8"

services:
  database:
    container_name: unifi-voucher-database
    image: mysql
    environment:
      MYSQL_DATABASE: DATABASE
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
    volumes:
      - db-data:/var/lib/mysql
      
  frontend:
    container_name: unifi-voucher-frontend
    image: unifi-voucher-frontend
    # enviroment variables dont actually do anything, u have to define them in .env or via the Build Arguments
    build:
      context: ./frontend
      target: production
      args:
        REACT_APP_BACKEND_PORT: 3000
        REACT_APP_BACKEND_URL: http://localhost
        REACT_APP_SYSTEM_NAME: UniFi Voucher System
        REACT_APP_GENERAL_ERROR_MESSAGE: Sorry, es gab nen Fehler, versuch das doch einfach nachher nochmal
        REACT_APP_NOT_FOUND_ERROR_MESSAGE: Sorry, wir haben leider nix gefunden
    ports:
      - 80:80
    volumes:
      - app-data:/app
    
  backend:
    container_name: unifi-voucher-backend
    image: unifi-voucher-backend
    restart: always
    environment:
      ACCESS_TOKEN_SECRET: LONG_RANDOM_CHARS
      REFRESH_TOKEN_SECRET: LONG_RANDOM_CHARS
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: ROOT_PASSWORD
      DB_DATABASE: DATABASE
      UNIFI_HOST: UNIFI_URL
      UNIFI_PORT: UNIFI_PORT
      UNIFI_USER: UNIFI_USER
      UNIFI_PASS: UNIFI_USER_PASSWORD
    depends_on:
      - database
    build:
      context: ./backend
    ports:
      - 3000:3000
    volumes:
      - app-data:/app

volumes:
  db-data:
  app-data: